name: Endor Labs Example
on: workflow_dispatch
jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '11'
      - name: Install Gradle Tools
        uses: gradle/gradle-build-action@v2
        with:
         gradle-version: 7.3
         cache-read-only: false
         cache-disabled: false
         cache-write-only: false
         generate-job-summary: true
         gradle-home-cache-strict-match: false
         gradle-home-cache-cleanup: false
         gradle-home-cache-includes: |
           caches
           notifications
      - name: Compile Package
        run: ./gradlew assemble
      - name: Scan with Endor Labs
        uses: endorlabs/github-action@main
        with:
          enable_github_action_token: false
          namespace: "yolo"
          api_key: ${{ secrets.ENDOR_API_CREDENTIALS_KEY }}
          api_secret: ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }}
